description: Film Favorit
name: fili

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  infinite_scroll_pagination: ^3.2.0
  geolocator: ^9.0.1
  carousel_slider: ^4.1.1
  flutter_local_notifications: ^9.7.0
  cached_network_image: ^3.2.1
  url_launcher: ^6.1.5
  fl_chart: ^0.55.0
  flutter_keyboard_visibility: ^5.3.0
  firebase_remote_config: ^2.0.12
  firebase_messaging: ^12.0.0
  cloud_firestore: ^3.3.0
  video_player: ^2.4.5
  equatable: ^2.0.3
  flutter_native_splash: ^2.2.4
  flutter_screenutil: ^5.5.3+2
  percent_indicator: ^4.2.2
  flutter_rating_bar: ^4.0.1
  in_app_review: ^2.0.4
  flutter_bloc: ^8.0.1
  flutter_gen: ^4.3.0
  dio: ^4.0.6
  alice: ^0.2.5
  flutter_svg: ^1.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.16.0

flutter:
  uses-material-design: true
