description: Film Favorit
name: fili

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  alice: ^0.2.5
  bloc: ^8.0.3
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.3.0
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  equatable: ^2.0.3
  firebase_messaging: ^12.0.0
  firebase_remote_config: ^2.0.12
  fl_chart: ^0.55.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_keyboard_visibility: ^5.3.0
  flutter_local_notifications: ^9.7.0
  flutter_native_splash: ^2.2.5
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.1+1
  geolocator: ^9.0.1
  get_it: ^7.2.0
  hive: ^2.2.3
  in_app_review: ^2.0.4
  infinite_scroll_pagination: ^3.2.0
  percent_indicator: ^4.2.2
  pretty_dio_logger: ^1.1.1
  url_launcher: ^6.1.5
  video_player: ^2.4.5

dev_dependencies:
  build_runner:
  dart_code_metrics: ^4.16.0
  flutter_gen_runner:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  melos: ^2.6.0
  flutter_launcher_icons: ^0.9.3

flutter:
  assets:
    - assets/
    - lib/secrets/.env
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
